# Generated by Django 5.2.7 on 2025-10-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='line_1',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=72, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
