# Generated by Django 5.2.7 on 2025-10-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_city_user_line_1_user_pincode_user_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='line_1',
            field=models.CharField(max_length=256, null=True, verbose_name='Address Line 1'),
        ),
    ]
